{% set name = "interrogate" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e8c5de9becb55fbcc549aa3da0200a0b84ed08404562b95397cde7e77de638e

build:
  number: 0
  noarch: python
  entry_points:
    - interrogate = interrogate.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - attrs
    - click
    - colorama
    - py
    - tabulate
    - toml

test:
  imports:
    - interrogate
  commands:
    - pip check
    - interrogate --help
  requires:
    - pip

about:
  home: https://interrogate.readthedocs.io
  summary: Interrogate a codebase for docstring coverage.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
